import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { db } from "./db/client";
import { env } from "./env";

/**
 * Better Auth — Google OAuth only. No passwords means no reset flow, no verification emails,
 * no credential storage (docs/02-tech-stack.md). Users live in our own Postgres via the
 * Drizzle adapter; the auth tables are generated by the Better Auth CLI into
 * lib/db/auth-schema.ts and must not be hand-edited.
 */
export const auth = betterAuth({
  baseURL: env.BETTER_AUTH_URL,
  secret: env.BETTER_AUTH_SECRET,
  database: drizzleAdapter(db, { provider: "pg" }),
  emailAndPassword: { enabled: false },
  socialProviders: {
    google: {
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
    },
  },
  // Ensures cookies set during server actions / route handlers are forwarded correctly in the
  // Next.js App Router.
  plugins: [nextCookies()],
});
