import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { MIN_PASSWORD_LENGTH } from "./auth-credentials";
import { db } from "./db/client";
import { env } from "./env";

/**
 * Better Auth — Google OAuth plus email/password. Users live in our own Postgres via the Drizzle
 * adapter; the auth tables are generated by the Better Auth CLI into lib/db/auth-schema.ts and
 * must not be hand-edited.
 *
 * docs/02-tech-stack.md originally specified Google only, on the reasoning that no passwords
 * means no reset flow, no verification emails and no credential storage — and said to "add email
 * sign-in later only if users ask for it". This is that later. The doc has been updated to match.
 *
 * NO MIGRATION WAS NEEDED. The Better Auth CLI already scaffolded `account.password` and the
 * `verification` table in migration 0000, even with email/password disabled, so enabling it is a
 * configuration change only — nothing was added, altered or dropped in the database.
 *
 * Passwords are hashed by Better Auth (scrypt via node:crypto) and stored in `account.password`.
 * This project never sees, hashes, compares or logs a password, and must not start.
 */
export const auth = betterAuth({
  baseURL: env.BETTER_AUTH_URL,
  secret: env.BETTER_AUTH_SECRET,
  database: drizzleAdapter(db, { provider: "pg" }),

  emailAndPassword: {
    enabled: true,
    /** Better Auth's own default, adopted rather than invented. Shared with the sign-up form. */
    minPasswordLength: MIN_PASSWORD_LENGTH,
    /** Sign-up issues a session directly, so a new account lands in the workspace, as Google does. */
    autoSignIn: true,
    /**
     * Email verification is NOT configured: there is no transactional email provider in this
     * stack (docs/02-tech-stack.md), and Better Auth would silently accept a `sendVerificationEmail`
     * that goes nowhere. Requiring verification here would therefore lock every new account out.
     * See the account-linking note below for the security consequence this has.
     */
    requireEmailVerification: false,
  },

  socialProviders: {
    // Unchanged. The existing Google flow, its client credentials and its callback are untouched.
    google: {
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
    },
  },

  /**
   * ACCOUNT LINKING — deliberately left at Better Auth's safe defaults.
   *
   * Better Auth will only implicitly link an OAuth login to an existing user when that user's
   * LOCAL email is already verified (`accountLinking.requireLocalEmailVerified`, default true).
   * Because this project has no email verification, that condition is never met, so an
   * email/password account is never auto-merged with a Google login. The user is redirected back
   * with `?error=account_not_linked`, which the sign-in page explains in plain language.
   *
   * Setting `requireLocalEmailVerified: false` would make that merge "just work", and is exactly
   * the change not to make: with unverified sign-up, an attacker can register victim@gmail.com
   * with a password they choose BEFORE the victim ever uses Google. The victim's Google sign-in
   * would then be linked into the attacker's account, handing them the victim's workspace. The
   * inconvenience of the current behaviour is the price of closing that, and the fix is email
   * verification — not looser linking.
   */

  /**
   * Better Auth's own limiter. `/api/auth/*` is deliberately exempt from the application limiter
   * (app/api/rate-limit-coverage.test.ts) precisely because this exists; adding `withRateLimit`
   * on top would be a second limiter over the same routes.
   *
   * The global default (100 requests / 10s) is fine for session reads but far too generous for a
   * password guess. These two rules narrow the credential endpoints specifically.
   *
   * Caveat, worth knowing rather than hiding: the default store is in-memory, so on Cloud Run the
   * budget is per instance and resets on cold start. It raises the cost of a brute-force attempt
   * without being an absolute ceiling. A shared store would need its own table and migration.
   */
  rateLimit: {
    customRules: {
      "/sign-in/email": { window: 60, max: 10 },
      "/sign-up/email": { window: 60, max: 5 },
    },
  },

  // Ensures cookies set during server actions / route handlers are forwarded correctly in the
  // Next.js App Router.
  plugins: [nextCookies()],
});
