import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";
import { OG_IMAGES, TWITTER_IMAGES } from "@/lib/seo";

const DESCRIPTION =
  "Edgify's output is generated by AI. It can be wrong, and it is not professional advice — " +
  "what that means for how you should use it.";

export const metadata: Metadata = {
  title: "AI Disclaimer",
  description: DESCRIPTION,
  alternates: { canonical: "/ai-disclaimer" },
  openGraph: {
    title: "AI Disclaimer — Edgify",
    description: DESCRIPTION,
    url: "/ai-disclaimer",
    type: "article",
    images: OG_IMAGES,
  },
  twitter: { card: "summary_large_image", title: "AI Disclaimer — Edgify", description: DESCRIPTION, images: TWITTER_IMAGES },
};

/**
 * Capabilities named here are exactly those the repository implements — the nine revision
 * formats including quizzes (lib/notes), the concept dependency graph with per-concept
 * explanations, flashcards and readiness scoring (lib/graph, lib/ai/schemas.ts). Nothing
 * aspirational is listed.
 */
export default function AiDisclaimerPage() {
  return (
    <LegalPage
      title="AI Disclaimer"
      intro="Everything Edgify generates is produced by automated language models. This page explains what that means in practice, and where the limits are."
      currentPath="/ai-disclaimer"
    >
      <h2>1. Edgify&apos;s output is AI-generated</h2>
      <p>Automated language models produce all of the following:</p>
      <ul>
        <li>Revision notes, key points, exam points, summaries and formula sheets</li>
        <li>Multiple-choice questions, quizzes and flashcards</li>
        <li>The concept dependency graph, including which concepts depend on which</li>
        <li>Per-concept explanations</li>
        <li>Learning-readiness scores derived from that graph</li>
      </ul>
      <p>
        None of it is written or reviewed by a subject expert, and none of it is checked by Edgify
        before you see it.
      </p>

      <h2>2. It can be wrong</h2>
      <p>
        Language models produce fluent text regardless of whether that text is correct.{" "}
        <strong>
          Output may be inaccurate, incomplete, outdated, internally inconsistent, or confidently
          wrong.
        </strong>{" "}
        This is a property of the technology, not a fault that will be fixed.
      </p>
      <p>Concretely, in Edgify this can mean:</p>
      <ul>
        <li>A summary omits something your examiner considers essential.</li>
        <li>A stated formula, date, definition or figure is incorrect.</li>
        <li>A quiz marks a correct answer wrong, or an incorrect answer right.</li>
        <li>
          The graph places concepts in the wrong order, or invents a dependency your course does
          not have.
        </li>
        <li>An explanation adds detail that is not in your source material.</li>
        <li>
          A readiness score suggests you are prepared for a topic when you are not. These scores
          are derived from generated structure and your own self-reported progress — they are not
          an assessment of your knowledge.
        </li>
      </ul>

      <h2>3. Verify before you rely on it</h2>
      <p>
        Treat Edgify&apos;s output as a study aid to be checked, not as a source of truth.{" "}
        <strong>
          Always verify anything that matters against your own lecture notes, textbooks, course
          materials and teaching staff.
        </strong>{" "}
        Your original material is authoritative; the generated version is not.
      </p>
      <p>
        Edgify generates from the material you supply, which reduces invention but does not
        eliminate it. Poor quality, incomplete or badly extracted source text produces poor quality
        output.
      </p>

      <h2>4. Not professional advice</h2>
      <p>
        Edgify is an educational tool. Its output is{" "}
        <strong>
          not medical, legal, financial, safety, engineering, or any other form of professional
          advice
        </strong>
        , and must not be relied on as such — including where you are studying those subjects.
        Consult a qualified professional for advice you intend to act on.
      </p>

      <h2>5. Academic integrity is your responsibility</h2>
      <p>
        Institutions differ in what use of AI tools they permit. Submitting AI-generated work as
        your own may breach your institution&apos;s rules.{" "}
        <strong>Knowing and following those rules is your responsibility.</strong>
      </p>

      <h2>6. No guarantee</h2>
      <p>
        Edgify does not guarantee the correctness, completeness, suitability or availability of any
        generated output, and does not guarantee any academic result. Generation depends on
        third-party AI providers and may fail, be delayed, be limited by daily quotas, or return a
        lower-quality result when a provider is unavailable.
      </p>

      <h2>7. Where your material goes</h2>
      <p>
        Generating output requires sending the text you provide to a third-party AI provider. What
        that involves — and what Edgify can and cannot promise about it — is set out in the{" "}
        <a href="/privacy">Privacy Policy</a>. If material is confidential, do not submit it.
      </p>
    </LegalPage>
  );
}
